version: '3.7'
services:
  edu-cl-mail-front:
    restart: always
    build:
      context: .
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.edu-cl-mail-front-stripprefix.stripPrefix.prefixes=/edu-cl-mail"
      - "traefik.http.routers.edu-cl-mail-front.rule=(Host(`krzysztofruczkowski.pl`) && PathPrefix(`/edu-cl-mail`))"
      - "traefik.http.routers.edu-cl-mail-front.middlewares=edu-cl-mail-front-stripprefix"
      - "traefik.http.routers.edu-cl-mail-front.tls=true"
      - "traefik.http.routers.edu-cl-mail-front.tls.certresolver=myresolver"
      - "traefik.http.services.edu-cl-mail-front.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"

networks:
  web:
    name: traefik_default
    external: true
